/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pt.up.fe.rvau.euromatch.ui;

import java.awt.Frame;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.opencv.core.Mat;
import org.opencv.highgui.Highgui;
import org.opencv.highgui.VideoCapture;
import pt.up.fe.rvau.euromatch.BillDetector;
import pt.up.fe.rvau.euromatch.DetectedBillsResult;
import pt.up.fe.rvau.euromatch.jutils.ImageConverter;

/**
 *
 * @author luiscubal
 */
public class WebCamBillDetectorViewer extends javax.swing.JDialog {

	/**
	 * Creates new form WebCamBillDetectorViewer
	 */
	public WebCamBillDetectorViewer(Frame parent, boolean modal, final BillDetector detector) {
		super(parent, modal);
		initComponents();
		
		new Thread(new Runnable() {

			@Override
			public void run() {
				VideoCapture videoCapture = new VideoCapture(0);
				Mat image = new Mat();
				for (;;) {
					if (videoCapture.retrieve(image)) {
						final DetectedBillsResult result = detector.performDetection(image);
						SwingUtilities.invokeLater(new Runnable() {

							@Override
							public void run() {
								jLabel1.setText("Total: " + result.totalValue);
								try {
									BufferedImage image = ImageConverter.convert(result.outputImage, 600, 500);
									jLabel2.setIcon(new ImageIcon(image));
								} catch (IOException e) {
									e.printStackTrace();
								}
								pack();
							}
						});
					} else {
						JOptionPane.showMessageDialog(WebCamBillDetectorViewer.this, "Could not take image");
					}
				}
			}
		}).start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);
        getContentPane().add(jLabel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
